# This workflow will run Jemeter and commit the report back into the rpository
name: Execute Performace Test

#Condition to trigger the workflow - When PR is merged to the performance branch
on: push

jobs:
  action_build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone private repo
        run: git clone "https://'pavithra.murali':'$EXTERNAL_TOKEN'@innersource.accenture.com/scm/ctsmywdc/dominionenergy.git"
        env:
          EXTERNAL_TOKEN : 'CcwBHDfh1HDEgWggkXGGio2M88LKWa3dloF3nx'
