# This workflow will run Jemeter and commit the report back into the rpository
name: Execute Performace Test

#Condition to trigger the workflow - When PR is merged to the performance branch
on:
  pull_request:
    types: [ closed ]
    branches: [ performance ]

jobs:
  action_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'scm/ctsmywdc/dominionenergy'
          token: 'BBDC-MzIyNTc2NTQ2MTI3OkywEzFQhi6UMlUEIqePq4y88Y6G'
          path: 'regression'
          github-server-url: 'https://innersource.accenture.com'
