# This is a basic workflow to help you get started with Actions

name: Static Code Scan to check for quality

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "develop" ]
    
env:
  codeQualityValue : ${{ secrets.CODESCAN_THRESHOLD }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Checkout code scan
        uses: actions/checkout@v2
        with:
         repository: king-raj7/muleCodeScan
         token: ${{ secrets.GITHUBTOKEN }} # `GH_PAT` is a secret that contains your PAT
         path: muleCodeScan
         
      - name: Run code scan
        run: /bin/bash muleCodeScan/codescan.sh
      
      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: artifacts
          path: codecheck/results/*.pdf
        
      - name: Print values
        id: temp-vars
        run: |
          percentNumber=$(grep "%" codecheck/results/result.txt | sed -e 's/^[[:space:]]*//')
          codeQuality=${percentNumber%.*}
          echo "codeValue=${codeQuality}" >> $GITHUB_OUTPUT
          echo "Code Quality: ${codeQuality}"
          
      - name: Check Code Quality
        if: ${{ steps.temp-vars.outputs.codeValue < env.codeQualityValue }}
        run: exit 1
