# This workflow will run Jemeter and commit the report back into the rpository
name: ddb-ch-2-demo

#Condition to trigger the workflow - When PR is merged to the performance branch
on:
  pull_request:
    types: [ closed ]
    branches: [ performance ]

# Set environment variables
# ***************************************************************************************************************************************************************
# **************************************** DEVELOPERS ARE RESPONSIBLE IN MANAGING PARAMETERS BELOW THIS LINE **************************************************
# *************************************************************************************************************************************************************
env:
  jmxFilePath: "ops/testDemo.jmx"                               #The jmx file is placed in the repo along with it's relative path
  committerEmail: "pavithra.murali@accenture.com"               #Update the developer email id here 
  committerName: "Pavithra Murali"                              #Update the developer First and Last Name. This name is reflected in the commit     


# ***************************************************************************************************************************************************************
# **************************************** DO NOT MAKE ANY CHANGES TO THIS SCRIPT OR VALUES BELOW THIS POINT ****************************************************
# ***************************************************************************************************************************************************************

jobs:
  action_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      #*********************** Action to run and generate the JMeter Report and place it in the output folder*******************
      
      - name: Run JMeter Action on a test
        uses: rbhadti94/apache-jmeter-action@v0.5.0
        with:
          testFilePath: ${{ env.jmxFilePath }}
          outputReportsFolder: reports/
          args: "--loglevel INFO"  
      
      #*********************** Runs the script to zip the report generated and commit it back to the repository ****************
      
      - name: Zip the report file
        shell: bash
        run: bash ${{ github.workspace }}/.github/workflows/performance.sh
        env:
          workspace: ${{ github.workspace }}
      
      #************************************************************************************************************************
      - uses: jfrog/setup-jfrog-cli@v3
        env:
      # JFrog platform url
          JF_URL: https://takedaawsuseast.jfrog.io 
      # Basic authentication credentials
          JF_USER: ${{ secrets.DDB_JFROG_USER }}
          JF_PASSWORD: ${{ secrets.DDB_JFROG_PASSWORD }}
      - run: |
          jf rt ping
          cd ${{ github.workspace }}/ops
          find . -type f -name *.zip -exec jfrog rt u {} ddb-maven-local/7741a7b6-9fb1-4b4d-88da-62a1ae33d537/ddb-ch-2-demo{} \;
