name: Execute Performace Test

on:
  #push:
  #  branches:
  #    - master
  pull_request:
    types: [ closed ]
    branches: [ performance ]

env:
  sendEmail: false
  jmxFilePath: "ops/testDemo.jmx"
  committerEmail: "pavithra.murali@accenture.com"
  committerName: "Pavithra Murali"

jobs:
  action_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run JMeter Action on a test
        uses: rbhadti94/apache-jmeter-action@v0.5.0
        with:
          testFilePath: ${{ env.jmxFilePath }}
          outputReportsFolder: reports/
          args: "--loglevel INFO"  
      
      - name: Commit Jmeter report to repo
        shell: bash
        run: |
          echo "GITHUB_WORKSPACE=${{ github.workspace }}"
          cd ${{ github.workspace }}/ops
          mkdir -p Report/Jmeter/ 
          cp -R ${{ github.workspace }}/reports ${{ github.workspace }}/ops/Report/Jmeter/
          cd ${{ github.workspace }}/ops/Report/Jmeter
          zip -r JMeterReport_`date +"%Y%m%d%H%M%S"` reports
          rm -r reports
          git config --global user.email "${{ env.committerEmail }}"
          git config --global user.name "${{ env.committerName }}"
          git add .
          git commit -m "Jmeter Report"
          git push
