name: Execute Performace Test

on:
  #push:
  #  branches:
  #    - master
  pull_request:
    types: [ closed ]
    branches: [ performance ]

env:
  sendEmail: true

jobs:
  action_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run JMeter Action on a test
        uses: rbhadti94/apache-jmeter-action@v0.5.0
        with:
          testFilePath: ops/testDemo.jmx
          outputReportsFolder: reports/
          args: "--loglevel INFO"  
      
      - name: Commit Jmeter report to repo
        shell: bash
        run: |
          echo "GITHUB_WORKSPACE=${{ github.workspace }}"
          cd ${{ github.workspace }}/ops
          mkdir -p Report/Jmeter/ 
          cp ${{ github.workspace }}/reports/statistics.json ${{ github.workspace }}/ops/Report/Jmeter/statistics_`date +"%Y%m%d"`.json
          cd ${{ github.workspace }}/ops/Report/Jmeter
          git config --global user.email "pavithra.murali@accenture.com"
          git config --global user.name "Pavithra Murali"
          git add .
          git commit -m "Jmeter Report1"
          git push
