name: Execute Performace Test

on:
  #push:
  #  branches:
  #    - master
  pull_request:
    types: [ closed ]
    branches: [ performance ]

env:
  sendEmail: true

jobs:
  action_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run JMeter Action on a test
        uses: rbhadti94/apache-jmeter-action@v0.5.0
        with:
          testFilePath: ops/testDemo.jmx
          outputReportsFolder: reports/
          args: "--loglevel INFO"


      - name: Commit Jmeter report to repo
        run: |
          cd reports/
          ls -1 > fileslist.txt
          cat filelist.txt
          mv statistics.json ./ops/Report/Jmeter/statistics_`date +"%Y%m%d"`.json
          cd ./ops/Report/Jmeter
          git add .
          git commit -m "Jmeter Report"
          git push origin performance
